version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  docker-executor:
    docker:
      - image: cimg/node:18.19.0
  sonar-scanner:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            npm ci
            npm run build
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker image
          command: |
            docker build -t ${DOCKER_USERNAME}/moxakk-analyzer:latest .
      - sonarcloud/scan

  push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push ${DOCKER_USERNAME}/moxakk-analyzer:latest

  deploy:
    docker:
      - image: cimg/base:2023.06
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:epkugIY3IvzkcZuf3b1hweoN2oANHwE+jiZT4J7LU1g"
      - run:
          name: Add server to known hosts
          command: |
            mkdir -p ~/.ssh
            echo $SSH_HOST_KEY >> ~/.ssh/known_hosts
      - run:
          name: Deploy to server
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/kutaykaracair/moxakk-analyzer-prod && \
            docker pull ${DOCKER_USERNAME}/moxakk-analyzer:latest && \
            docker-compose --env-file .env down || true && \
            docker-compose --env-file .env up -d"

workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - docker-hub-creds
            - SonarCloud
      - push:
          requires:
            - build
          context: docker-hub-creds
      - deploy:
          requires:
            - push
          context: ssh-deployment